# curl -u premysl.vyhnal@gmail.com   -d '{"scopes":["public_repo"],"note":"tangram travis"}'   https://api.github.com/authorizations


language: bash
sudo: false
install: true
addons:
  apt:
    packages:
    - lua5.1
    - python2.7
script: "./build.sh web"
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    # travis encrypt <token>
    secure: "Ofqc3aM2sMADduJPMc9v6wMFZDTqZdgnBZtEmUE7tAJqM4pE09pFCX1qZnGalMMu6iRZNKCfDQ0/mYHTxjOL6kTMYmwWDu+F4GZP1S4r+exLHXJDkXGHFIhDVbYNy4dejlDAAgJNhn0v468Tl7Y5PqdBmcT1YCpg9W6kEju+0vtrVHEHto2kJWhzFSLfflgUIt2DoyUY2Uy1MTv2tA8ZQPvE9kSDBnI4adxj3hYnwNC8imACQvwDoyOMI+W7xABdjHy0bwEH2tgyDWDl2NqLuOERqyUYrn/+ZEGMNAwQ34cI+8S4vtzTgjkIRj48SBATTsGbn83WO3lTrC9iuO7RWSqULvwwJQmGwWpHC5gD8TYwsAta+12lppWnUX2gEK5vveUnI1F6QbDfWUrPE+Ciw+esZj4qygth8kDdP1NjdswLcKX0fsuLJi67UpMZ1SHBYPROCRZ5wlAjGAjT/xN1Au1IYm8cp+/vrOreki3SI4ftIN24OiUiDIBKWU17pL5X2pakmsceqs9OBdnb9g+1nS/D/4n6/Zf7VYY4qriWnR8BRXIIQLcn1DYba++aDgKTaR6Q6fbvEmq02E2+YsKvDK34VaGO5XLMhtGGP6r4t2utmqW1VymaxFj7D82zIjUK0SYqZw0sieovFx8i6mknxmccnKrM5ZuE02Z6jat9V2o="
  file:
  - target/Tangram.love
  - target/Tangram-win.zip
  - target/Tangram-web.zip
  on:
    tags: true
    all_branches: true
after_success:
- "[[ -n $TRAVIS_TAG ]] && ./build.sh deploy premek/tangram"
env:
  global:
   # travis encrypt GH_TOKEN=<token>
  - secure: "KUx8l8GjT6LF7aRZIa7CYjlvHxF3sXFMvkajhKRzPcRsJ/EwAfLMlU0kntrnphTsbp6HR6+vAtwEcBNDF9ddmj1UbTUTF35jyrRckMvd/q0R3WPTdApvksNjoRHCTHJVYTkGreG3kiC5IqSx905ItpHx+6Dx4tqxvreZnwSQkD2ASWfd+aKy3tVdDa+X7xi6Q287bYae7u7JoHnWftspAPnwK5wayuk6lTIDCeBDWphzCsy/J31ZLguGA+BeF1c8PACepzdDnm37htTWai0bdbSERxJX6+RKvtFNtXhF1BD39lN5DgZQEdHicGBr8Z3HoeGFb0YMzkpdSjYidkaeQSONtvi4a6cFtXw+uEgE+JjZFX81KaIwD4EFHXU3h/ZhbcGA6Zbc5Z2zU/uIXCJ0zVhCZE4j97ZXGDF/PV2//Lx1cBGyHLIJ6lK5B7v6U3fzMqw/rgau4rtnipRpMTqYhb4y3qOMlQZoxKUGzCR/n1ladjozCyuvHpM8F41oFaDM61IznMgr380L6qyHOWg2f/RvBDvRyt3jcgSN2n26cWRzjPj6Zu9SmFte7vPUrD+1lGSE7E5NzLzHPY1FRAJa3MEYpbFTGXphhVZzBuf9TV86qw8mS/4kTF34e668HejTFR7RT8kukjGhcfo8fza7hyupl4+UC5GUxJQ1CiPqJM8="
